### PR TITLE
Make overcharged blasters blow the heck up

### PR DESCRIPTION
**Pull request by RojjaCebolla**

### CODE REVIEW

**Review by NeroOneTrueKing — COMMENTED** [review]
Nice! I feel like the message should be printed before the explosion happens, though.

**Comment by RojjaCebolla** [comment]
Cool, I'll change that.

Riker helped me build DNH correctly, so it turns out the game doesn't even allow *attempting* to charge a blaster for the 5th time. Which maybe means that "if >= 4" check was probably never actually needed/checked?

I'll keep hunting for the way to make it happen, unless you know what the prob might be.

**Comment by RojjaCebolla** [comment]
oh, nevermind, it works! i just needed to **start a fresh game** after recompiling

**Comment by RojjaCebolla** [comment]
yay, finally got rid of the dup commits from upstream. don't git pull in a PR branch, folks!

**Comment by RojjaCebolla** [comment]
actually i'm not done with this, it should warn you once before the gun blows up

**Comment by RojjaCebolla** [comment]
ok, all done!

**Review by NeroOneTrueKing — APPROVED** [review]

**Comment by Chris-plus-alphanumericgibberish** [comment]
I'm closing this version because it's against 3.21.1

Copypasta from the issue:

I mentioned this in chat a while ago, but the issue with https://github.com/Chris-plus-alphanumericgibberish/dNAO/pull/1763 is that blaster charge limits are referencing a second ammo type rather than overheating.

However, I'm still on board with incorporating it in some form. For instance, perhaps charging an already-charged blaster might cause it to explode.

**Pull request closed without merging**
